on:
  workflow_dispatch:
  push:
    branches: [main, master]
  # pull_request:
  #   branches: [main, master]
  # schedule:
  #   # 4a EDT (in UTC) for waiver run
  #   - cron: '0 8 * 9-12,1-2 0-6'
  #   # 12p EDT TUE for week final scores
  #   - cron: '0 16 * 9-12,1-2 2'

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Select R Version
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1' # The R version to download (if necessary) and use.
          
      - name: Install system dependencies
        run: sudo apt install libcurl4-openssl-dev
          
      - name: Load Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      # # from https://rstudio.github.io/renv/articles/ci.html
      # - name: Restore packages
      #   shell: Rscript {0}
      #   run: |
      #     if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
      #     renv::restore()

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}